version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: sms-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=stock-management

volumes:
  mongodb_data:
